export const MOVIES_ACTION_TYPES = {
    SET_MOVIES_START: 'movies/SET_MOVIES_START',
    SET_MOVIES_SUCCESS: 'movies/SET_MOVIES_SUCCESS',
    SET_MOVIES_FAILURE: 'movies/SET_MOVIES_FAILURE',
    SET_TOTAL_PAGES: 'movies/SET_TOTAL_PAGES',
    SET_CURRENT_PAGE: 'movies/SET_CURRENT_PAGE',
}