export const MOVIES_ACTION_TYPES = {
    SET_MOVIES_START: 'movies/SET_MOVIES_START',
    SET_MOVIES_SUCCESS: 'movies/SET_MOVIES_SUCCESS',
    SET_MOVIES_FAILURE: 'movies/SET_MOVIES_FAILURE',
    SET_CURRENT_PAGE: 'movies/SET_CURRENT_PAGE',
    SET_NOMINATED_MOVIE: 'movies/SET_NOMINATED_MOVIE',
    SET_SHOW_NOMINATED: 'movies/SET_SHOW_NOMINATED'
}